name: GCP Artifact Registry Deployment
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        python-version: [ "3.11" ]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install build twine
      - name: Build Python package
        run: |
          python -m build
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          token_format: "access_token"
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: set  Artifact Registry
        run: |
          gcloud config set artifacts/repository '${{ secrets.ARTIFACT_REPOSITORY }}'
          gcloud config set artifacts/location '${{ secrets.ARTIFACT_LOCATION }}'
          gcloud config set account '${{ secrets.SERVICE_ACCOUNT }}'
          echo $GOOGLE_GHA_CREDS_PATH "hello" $GOOGLE_APPLICATION_CREDENTIALS
          
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud artifacts print-settings python > ~/.pypirc

          python -m twine upload --verbose --repository ${{ secrets.ARTIFACT_REPOSITORY }} dist/*
        env:
          key: base64 -i $GOOGLE_GHA_CREDS_PATH